Nogrod\eBaySDK\Finding\ProductIdType:
    virtual_properties:
        ns_prop:
            exp: '"http://www.ebay.com/marketplace/search/v1/services"'
            serialized_name: xmlns
            xml_attribute: true
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
            xml_element:
                cdata: false
        type:
            expose: true
            access_type: public_method
            serialized_name: type
            accessor:
                getter: getType
                setter: setType
            xml_attribute: true
            type: string
