<?php

namespace Nogrod\eBaySDK\BulkDataExchange;

use Nogrod\XMLClientRuntime\Func;

/**
 * Class representing CreateRecurringJobRequestType
 *
 * Creates a recurring Bulk Data Exchange job and assigns it a <b>recurringJobId</b>.
 *  When you create a recurring job, you must specify a recurrence interval, such
 *  as daily, weekly, monthly, or a frequency in minutes.
 *  <br><br>
 *  Once a recurring job has been created, a separate job ID is created for each
 *  job that is created/executed. For example, if a job runs every hour, it will
 *  have a single <b>recurringJobId</b> and each hourly job
 *  will have a unique <b>jobId</b> and <b>fileReferenceId</b>.
 * XSD Type: CreateRecurringJobRequest
 */
class CreateRecurringJobRequestType extends BaseServiceRequestType
{

    /**
     * A Universally Unique Identifier (UUID) provided by the seller's
     *  application.
     *
     * @var string $uUID
     */
    private $uUID = null;

    /**
     * Specifies the filters for creating recurring jobs for different LMS downlaod job types
     *
     * @var \Nogrod\eBaySDK\BulkDataExchange\DownloadJobRecurringFilterType $downloadJobRecurringFilter
     */
    private $downloadJobRecurringFilter = null;

    /**
     * Use this field to set up a recurring job that happens more than once a day. After the initial job instance is executed, the subsequent job instances will be executed according to the frequency (in minutes) set in the <b>frequencyInMinutes</b> field.
     *  <br><br>
     *  If this field is used, the <b>weeklyRecurrence</b> and <b>dailyRecurrence</b> and <b>monthlyRecurrence</b> containers should not be used.
     *
     * @var int $frequencyInMinutes
     */
    private $frequencyInMinutes = null;

    /**
     * Specifies the report you want to download. Each Bulk Data Exchange
     *  job can only have one job type per job. For instance, if you are
     *  downloading a <b>SoldReport</b>, it will only have predefined <b>SoldReport</b>
     *  data within the file.
     *
     *  <br><br>
     *  <dl>
     *  <lh><b>Applicable values</b>:<br></lh>
     *
     *  <dt><b>ActiveInventoryReport</b></dt>
     *  <dd>A report that contains all of the active listings for a specific
     *  seller ID. The eBay servers read the credential information passed in by
     *  the seller's application to determine which seller's data to retrieve.
     *  </dd>
     *
     *  <dt><b>FeeSettlementReport</b></dt>
     *  <dd>A report that contains all of the fees that you have incurred
     *  as invoices are generated by the eBay servers. This report gives large
     *  merchants the ability to look at their fees for many listings in one file.
     *  </dd>
     *
     *  <dt><b>SoldReport</b></dt>
     *  <dd>Lists all items that have been sold by this seller (sold items
     *  that were submitted to the Large Merchant Service by the seller's
     *  application).
     *  <br><br>
     *  When an item is sold, the eBay application creates an 'order' for the
     *  seller. If only one item is sold, there is one order ID and one line item
     *  ID associated with the sale. However, if multiple items are sold as part
     *  of the same transaction, there is one order ID for the sale, and multiple
     *  line item IDs - one line item ID for each item sold.
     *  <br><br>
     *  Therefore, <b>SoldReport</b> returns the order IDs and line item IDs for
     *  every order associated with the seller who is making the request. Sellers
     *  use this information to make inventory updates and start order fulfillment.
     *  <br><br>
     *  When orders have been fulfilled, the seller will probably want to remove
     *  them from the list of all orders that comes back every time they receive a
     *  <b>SoldReport</b>. To do this, they can acknowledge each order that has been
     *  fulfilled (using order ID or line item ID) by uploading a list of the
     *  fulfilled order information using an <b>OrderAck</b> request.
     *  <br><br>
     *  After you upload a data file with an <b>OrderAck</b> request, the orders (or line
     *  items within an order) will no longer appear in <b>SoldReport</b>. After you
     *  send the first <b>OrderAck</b> call, future <b>SoldReport</b> responses will only
     *  contain unacknowledged orders and line items.
     *  </dd>
     *
     *  </dl>
     *
     * @var string $downloadJobType
     */
    private $downloadJobType = null;

    /**
     * Optional container that can be used to create a recurring job that is executed on a monthly basis. If this container is used, the <b>weeklyRecurrence</b> and <b>dailyRecurrence</b> containers should not be used.
     *
     * @var \Nogrod\eBaySDK\BulkDataExchange\MonthlyRecurrenceType $monthlyRecurrence
     */
    private $monthlyRecurrence = null;

    /**
     * Optional container that can be used to create a recurring job that is executed on a weekly basis. If this container is used, the <b>monthlyRecurrence</b> and <b>dailyRecurrence</b> containers should not be used.
     *
     * @var \Nogrod\eBaySDK\BulkDataExchange\WeeklyRecurrenceType $weeklyRecurrence
     */
    private $weeklyRecurrence = null;

    /**
     * Optional container that can be used to create a recurring job that is executed on a weekly basis. If this container is used, the <b>weeklyRecurrence</b> and <b>monthlyRecurrence</b> containers should not be used.
     *
     * @var \Nogrod\eBaySDK\BulkDataExchange\DailyRecurrenceType $dailyRecurrence
     */
    private $dailyRecurrence = null;

    /**
     * Gets as uUID
     *
     * A Universally Unique Identifier (UUID) provided by the seller's
     *  application.
     *
     * @return string
     */
    public function getUUID()
    {
        return $this->uUID;
    }

    /**
     * Sets a new uUID
     *
     * A Universally Unique Identifier (UUID) provided by the seller's
     *  application.
     *
     * @param string $uUID
     * @return self
     */
    public function setUUID($uUID)
    {
        $this->uUID = $uUID;
        return $this;
    }

    /**
     * Gets as downloadJobRecurringFilter
     *
     * Specifies the filters for creating recurring jobs for different LMS downlaod job types
     *
     * @return \Nogrod\eBaySDK\BulkDataExchange\DownloadJobRecurringFilterType
     */
    public function getDownloadJobRecurringFilter()
    {
        return $this->downloadJobRecurringFilter;
    }

    /**
     * Sets a new downloadJobRecurringFilter
     *
     * Specifies the filters for creating recurring jobs for different LMS downlaod job types
     *
     * @param \Nogrod\eBaySDK\BulkDataExchange\DownloadJobRecurringFilterType $downloadJobRecurringFilter
     * @return self
     */
    public function setDownloadJobRecurringFilter(\Nogrod\eBaySDK\BulkDataExchange\DownloadJobRecurringFilterType $downloadJobRecurringFilter)
    {
        $this->downloadJobRecurringFilter = $downloadJobRecurringFilter;
        return $this;
    }

    /**
     * Gets as frequencyInMinutes
     *
     * Use this field to set up a recurring job that happens more than once a day. After the initial job instance is executed, the subsequent job instances will be executed according to the frequency (in minutes) set in the <b>frequencyInMinutes</b> field.
     *  <br><br>
     *  If this field is used, the <b>weeklyRecurrence</b> and <b>dailyRecurrence</b> and <b>monthlyRecurrence</b> containers should not be used.
     *
     * @return int
     */
    public function getFrequencyInMinutes()
    {
        return $this->frequencyInMinutes;
    }

    /**
     * Sets a new frequencyInMinutes
     *
     * Use this field to set up a recurring job that happens more than once a day. After the initial job instance is executed, the subsequent job instances will be executed according to the frequency (in minutes) set in the <b>frequencyInMinutes</b> field.
     *  <br><br>
     *  If this field is used, the <b>weeklyRecurrence</b> and <b>dailyRecurrence</b> and <b>monthlyRecurrence</b> containers should not be used.
     *
     * @param int $frequencyInMinutes
     * @return self
     */
    public function setFrequencyInMinutes($frequencyInMinutes)
    {
        $this->frequencyInMinutes = $frequencyInMinutes;
        return $this;
    }

    /**
     * Gets as downloadJobType
     *
     * Specifies the report you want to download. Each Bulk Data Exchange
     *  job can only have one job type per job. For instance, if you are
     *  downloading a <b>SoldReport</b>, it will only have predefined <b>SoldReport</b>
     *  data within the file.
     *
     *  <br><br>
     *  <dl>
     *  <lh><b>Applicable values</b>:<br></lh>
     *
     *  <dt><b>ActiveInventoryReport</b></dt>
     *  <dd>A report that contains all of the active listings for a specific
     *  seller ID. The eBay servers read the credential information passed in by
     *  the seller's application to determine which seller's data to retrieve.
     *  </dd>
     *
     *  <dt><b>FeeSettlementReport</b></dt>
     *  <dd>A report that contains all of the fees that you have incurred
     *  as invoices are generated by the eBay servers. This report gives large
     *  merchants the ability to look at their fees for many listings in one file.
     *  </dd>
     *
     *  <dt><b>SoldReport</b></dt>
     *  <dd>Lists all items that have been sold by this seller (sold items
     *  that were submitted to the Large Merchant Service by the seller's
     *  application).
     *  <br><br>
     *  When an item is sold, the eBay application creates an 'order' for the
     *  seller. If only one item is sold, there is one order ID and one line item
     *  ID associated with the sale. However, if multiple items are sold as part
     *  of the same transaction, there is one order ID for the sale, and multiple
     *  line item IDs - one line item ID for each item sold.
     *  <br><br>
     *  Therefore, <b>SoldReport</b> returns the order IDs and line item IDs for
     *  every order associated with the seller who is making the request. Sellers
     *  use this information to make inventory updates and start order fulfillment.
     *  <br><br>
     *  When orders have been fulfilled, the seller will probably want to remove
     *  them from the list of all orders that comes back every time they receive a
     *  <b>SoldReport</b>. To do this, they can acknowledge each order that has been
     *  fulfilled (using order ID or line item ID) by uploading a list of the
     *  fulfilled order information using an <b>OrderAck</b> request.
     *  <br><br>
     *  After you upload a data file with an <b>OrderAck</b> request, the orders (or line
     *  items within an order) will no longer appear in <b>SoldReport</b>. After you
     *  send the first <b>OrderAck</b> call, future <b>SoldReport</b> responses will only
     *  contain unacknowledged orders and line items.
     *  </dd>
     *
     *  </dl>
     *
     * @return string
     */
    public function getDownloadJobType()
    {
        return $this->downloadJobType;
    }

    /**
     * Sets a new downloadJobType
     *
     * Specifies the report you want to download. Each Bulk Data Exchange
     *  job can only have one job type per job. For instance, if you are
     *  downloading a <b>SoldReport</b>, it will only have predefined <b>SoldReport</b>
     *  data within the file.
     *
     *  <br><br>
     *  <dl>
     *  <lh><b>Applicable values</b>:<br></lh>
     *
     *  <dt><b>ActiveInventoryReport</b></dt>
     *  <dd>A report that contains all of the active listings for a specific
     *  seller ID. The eBay servers read the credential information passed in by
     *  the seller's application to determine which seller's data to retrieve.
     *  </dd>
     *
     *  <dt><b>FeeSettlementReport</b></dt>
     *  <dd>A report that contains all of the fees that you have incurred
     *  as invoices are generated by the eBay servers. This report gives large
     *  merchants the ability to look at their fees for many listings in one file.
     *  </dd>
     *
     *  <dt><b>SoldReport</b></dt>
     *  <dd>Lists all items that have been sold by this seller (sold items
     *  that were submitted to the Large Merchant Service by the seller's
     *  application).
     *  <br><br>
     *  When an item is sold, the eBay application creates an 'order' for the
     *  seller. If only one item is sold, there is one order ID and one line item
     *  ID associated with the sale. However, if multiple items are sold as part
     *  of the same transaction, there is one order ID for the sale, and multiple
     *  line item IDs - one line item ID for each item sold.
     *  <br><br>
     *  Therefore, <b>SoldReport</b> returns the order IDs and line item IDs for
     *  every order associated with the seller who is making the request. Sellers
     *  use this information to make inventory updates and start order fulfillment.
     *  <br><br>
     *  When orders have been fulfilled, the seller will probably want to remove
     *  them from the list of all orders that comes back every time they receive a
     *  <b>SoldReport</b>. To do this, they can acknowledge each order that has been
     *  fulfilled (using order ID or line item ID) by uploading a list of the
     *  fulfilled order information using an <b>OrderAck</b> request.
     *  <br><br>
     *  After you upload a data file with an <b>OrderAck</b> request, the orders (or line
     *  items within an order) will no longer appear in <b>SoldReport</b>. After you
     *  send the first <b>OrderAck</b> call, future <b>SoldReport</b> responses will only
     *  contain unacknowledged orders and line items.
     *  </dd>
     *
     *  </dl>
     *
     * @param string $downloadJobType
     * @return self
     */
    public function setDownloadJobType($downloadJobType)
    {
        $this->downloadJobType = $downloadJobType;
        return $this;
    }

    /**
     * Gets as monthlyRecurrence
     *
     * Optional container that can be used to create a recurring job that is executed on a monthly basis. If this container is used, the <b>weeklyRecurrence</b> and <b>dailyRecurrence</b> containers should not be used.
     *
     * @return \Nogrod\eBaySDK\BulkDataExchange\MonthlyRecurrenceType
     */
    public function getMonthlyRecurrence()
    {
        return $this->monthlyRecurrence;
    }

    /**
     * Sets a new monthlyRecurrence
     *
     * Optional container that can be used to create a recurring job that is executed on a monthly basis. If this container is used, the <b>weeklyRecurrence</b> and <b>dailyRecurrence</b> containers should not be used.
     *
     * @param \Nogrod\eBaySDK\BulkDataExchange\MonthlyRecurrenceType $monthlyRecurrence
     * @return self
     */
    public function setMonthlyRecurrence(\Nogrod\eBaySDK\BulkDataExchange\MonthlyRecurrenceType $monthlyRecurrence)
    {
        $this->monthlyRecurrence = $monthlyRecurrence;
        return $this;
    }

    /**
     * Gets as weeklyRecurrence
     *
     * Optional container that can be used to create a recurring job that is executed on a weekly basis. If this container is used, the <b>monthlyRecurrence</b> and <b>dailyRecurrence</b> containers should not be used.
     *
     * @return \Nogrod\eBaySDK\BulkDataExchange\WeeklyRecurrenceType
     */
    public function getWeeklyRecurrence()
    {
        return $this->weeklyRecurrence;
    }

    /**
     * Sets a new weeklyRecurrence
     *
     * Optional container that can be used to create a recurring job that is executed on a weekly basis. If this container is used, the <b>monthlyRecurrence</b> and <b>dailyRecurrence</b> containers should not be used.
     *
     * @param \Nogrod\eBaySDK\BulkDataExchange\WeeklyRecurrenceType $weeklyRecurrence
     * @return self
     */
    public function setWeeklyRecurrence(\Nogrod\eBaySDK\BulkDataExchange\WeeklyRecurrenceType $weeklyRecurrence)
    {
        $this->weeklyRecurrence = $weeklyRecurrence;
        return $this;
    }

    /**
     * Gets as dailyRecurrence
     *
     * Optional container that can be used to create a recurring job that is executed on a weekly basis. If this container is used, the <b>weeklyRecurrence</b> and <b>monthlyRecurrence</b> containers should not be used.
     *
     * @return \Nogrod\eBaySDK\BulkDataExchange\DailyRecurrenceType
     */
    public function getDailyRecurrence()
    {
        return $this->dailyRecurrence;
    }

    /**
     * Sets a new dailyRecurrence
     *
     * Optional container that can be used to create a recurring job that is executed on a weekly basis. If this container is used, the <b>weeklyRecurrence</b> and <b>monthlyRecurrence</b> containers should not be used.
     *
     * @param \Nogrod\eBaySDK\BulkDataExchange\DailyRecurrenceType $dailyRecurrence
     * @return self
     */
    public function setDailyRecurrence(\Nogrod\eBaySDK\BulkDataExchange\DailyRecurrenceType $dailyRecurrence)
    {
        $this->dailyRecurrence = $dailyRecurrence;
        return $this;
    }

    public function xmlSerialize(\Sabre\Xml\Writer $writer)
    {
        parent::xmlSerialize($writer);
        $value = $this->getUUID();
        if (null !== $value) {
            $writer->writeElement("{http://www.ebay.com/marketplace/services}UUID", $value);
        }
        $value = $this->getDownloadJobRecurringFilter();
        if (null !== $value) {
            $writer->writeElement("{http://www.ebay.com/marketplace/services}downloadJobRecurringFilter", $value);
        }
        $value = $this->getFrequencyInMinutes();
        if (null !== $value) {
            $writer->writeElement("{http://www.ebay.com/marketplace/services}frequencyInMinutes", $value);
        }
        $value = $this->getDownloadJobType();
        if (null !== $value) {
            $writer->writeElement("{http://www.ebay.com/marketplace/services}downloadJobType", $value);
        }
        $value = $this->getMonthlyRecurrence();
        if (null !== $value) {
            $writer->writeElement("{http://www.ebay.com/marketplace/services}monthlyRecurrence", $value);
        }
        $value = $this->getWeeklyRecurrence();
        if (null !== $value) {
            $writer->writeElement("{http://www.ebay.com/marketplace/services}weeklyRecurrence", $value);
        }
        $value = $this->getDailyRecurrence();
        if (null !== $value) {
            $writer->writeElement("{http://www.ebay.com/marketplace/services}dailyRecurrence", $value);
        }
    }

    public static function xmlDeserialize(\Sabre\Xml\Reader $reader)
    {
        return self::fromKeyValue($reader->parseInnerTree([]));
    }

    public static function fromKeyValue($keyValue)
    {
        $self = new self();
        $self->setKeyValue($keyValue);
        return $self;
    }

    public function setKeyValue($keyValue)
    {
        parent::setKeyValue($keyValue);
        $value = Func::mapArray($keyValue, '{http://www.ebay.com/marketplace/services}UUID');
        if (null !== $value) {
            $this->setUUID($value);
        }
        $value = Func::mapArray($keyValue, '{http://www.ebay.com/marketplace/services}downloadJobRecurringFilter');
        if (null !== $value) {
            $this->setDownloadJobRecurringFilter(\Nogrod\eBaySDK\BulkDataExchange\DownloadJobRecurringFilterType::fromKeyValue($value));
        }
        $value = Func::mapArray($keyValue, '{http://www.ebay.com/marketplace/services}frequencyInMinutes');
        if (null !== $value) {
            $this->setFrequencyInMinutes($value);
        }
        $value = Func::mapArray($keyValue, '{http://www.ebay.com/marketplace/services}downloadJobType');
        if (null !== $value) {
            $this->setDownloadJobType($value);
        }
        $value = Func::mapArray($keyValue, '{http://www.ebay.com/marketplace/services}monthlyRecurrence');
        if (null !== $value) {
            $this->setMonthlyRecurrence(\Nogrod\eBaySDK\BulkDataExchange\MonthlyRecurrenceType::fromKeyValue($value));
        }
        $value = Func::mapArray($keyValue, '{http://www.ebay.com/marketplace/services}weeklyRecurrence');
        if (null !== $value) {
            $this->setWeeklyRecurrence(\Nogrod\eBaySDK\BulkDataExchange\WeeklyRecurrenceType::fromKeyValue($value));
        }
        $value = Func::mapArray($keyValue, '{http://www.ebay.com/marketplace/services}dailyRecurrence');
        if (null !== $value) {
            $this->setDailyRecurrence(\Nogrod\eBaySDK\BulkDataExchange\DailyRecurrenceType::fromKeyValue($value));
        }
    }
}
