<?php

namespace Nogrod\eBaySDK\BulkDataExchange;

/**
 * Class representing StartUploadJobResponseType
 *
 * Type defining the root container of the <b>startUploadJob</b> response. The response includes the standard output fields like <b>ack</b>, <b>timestamp</b>, <b>version</b>, and any errors/warnings that are generated by the request to start an upload job.
 * XSD Type: StartUploadJobResponse
 */
class StartUploadJobResponseType extends BaseServiceResponseType
{
    public function xmlSerialize(\Sabre\Xml\Writer $writer): void
    {
        parent::xmlSerialize($writer);
    }

    public static function xmlDeserialize(\Sabre\Xml\Reader $reader)
    {
        return self::fromKeyValue($reader->parseInnerTree([]));
    }

    public static function fromKeyValue($keyValue)
    {
        $self = new self();
        $self->setKeyValue($keyValue);
        return $self;
    }

    public function setKeyValue($keyValue)
    {
        parent::setKeyValue($keyValue);
    }
}
