<?php

namespace Nogrod\eBaySDK\BulkDataExchange;

/**
 * Class representing SuspendRecurringJobResponseType
 *
 * Type defining the root container of the <b>suspendRecurringJob</b> response. The response includes the standard output fields like <b>ack</b>, <b>timestamp</b>, <b>version</b>, and any errors/warnings that are generated by the request to suspend the next scheduled recurring job. The <b>ack</b> values of 'Success' or 'Failure' will indicate whether or not the next scheduled recurring job was successfully suspended.
 * XSD Type: SuspendRecurringJobResponse
 */
class SuspendRecurringJobResponseType extends BaseServiceResponseType
{
    public function xmlSerialize(\Sabre\Xml\Writer $writer)
    {
        parent::xmlSerialize($writer);
    }

    public static function xmlDeserialize(\Sabre\Xml\Reader $reader)
    {
        return self::fromKeyValue($reader->parseInnerTree([]));
    }

    public static function fromKeyValue($keyValue)
    {
        $self = new self();
        $self->setKeyValue($keyValue);
        return $self;
    }

    public function setKeyValue($keyValue)
    {
        parent::setKeyValue($keyValue);
    }

    public static function mapArray(array $array, string $name, bool $isArray = false)
    {
        $result = [];
        foreach ($array as $item) {
            if ($item['name'] !== $name) {
                continue;
            }
            if ($isArray) {
                $result[] = $item['value'];
            } else {
                return $item['value'];
            }
        }
        return $isArray ? $result : null;
    }
}
