<?php

namespace Nogrod\eBaySDK\Trading;

use Nogrod\XMLClientRuntime\Func;

/**
 * Class representing CharityType
 *
 * This type is used to provide details about a nonprofit organization that will benefit from each sale generated from an eBay listing.
 * XSD Type: CharityType
 */
class CharityType implements \Sabre\Xml\XmlSerializable, \Sabre\Xml\XmlDeserializable, \JsonSerializable
{
    /**
     * The full name of the nonprofit organization.
     *  <br>
     *  <br>
     *
     * @var string $charityName
     */
    private $charityName = null;

    /**
     * The percentage of the purchase price that the
     *  seller chooses to donate to the selected nonprofit
     *  organization. This percentage is displayed in the eBay for Charity listing.
     *  <b>Possible values</b>: 10.0 to 100.0.
     *  <b></b>
     *  <ul>
     *  <li>Percentages must increment by 5.0. </li>
     *  <li>Minimum donation
     *  percentages may be required for eBay for Charity listings, see
     *  <a href="http://pages.ebay.com/help/sell/selling-nonprofit.html">
     *  Selling to benefit nonprofit organizations</a> for
     *  details. </li>
     *  </ul>
     *  The <b>DonationPercent</b> field is required in an Add/Revise/Relist call if the seller will be donating a percentage of the sale proceeds for each sale generated by the listing.
     *
     * @var float $donationPercent
     */
    private $donationPercent = null;

    /**
     * The unique identifier that eBay creates and assigns to each nonprofit organization.
     *  <br>
     *  <br>
     *  The field is conditionally required in an Add/Revise/Relist call if the seller will be donating a percentage of the sale proceeds to this organization for each sale generated by the listing.
     *
     * @var string $charityID
     */
    private $charityID = null;

    /**
     * The stated mission of the nonprofit charity organization. This mission statement is displayed in the eBay for Charity section of the View Item page.
     *  <br>
     *  <br>
     *
     * @var string $mission
     */
    private $mission = null;

    /**
     * The full URL to the nonprofit organization's logo image file. This logo image file is the image that is displayed in all eBay listings that benefit that charity. This field is returned as long as it is defined for the nonprofit organization.
     *
     * @var string $logoURL
     */
    private $logoURL = null;

    /**
     * This enumeration value indicates whether or not the nonprofit organization is a valid eBay for Charity organization, and is able to receive proceeds from eBay sales.
     *
     * @var string $status
     */
    private $status = null;

    /**
     * If this field is returned as <code>true</code>, a percentage of order line item's purchase price will be donated to a nonprofit organization.
     *
     * @var bool $charityListing
     */
    private $charityListing = null;

    /**
     * Gets as charityName
     *
     * The full name of the nonprofit organization.
     *  <br>
     *  <br>
     *
     * @return string
     */
    public function getCharityName()
    {
        return $this->charityName;
    }

    /**
     * Sets a new charityName
     *
     * The full name of the nonprofit organization.
     *  <br>
     *  <br>
     *
     * @param string $charityName
     * @return self
     */
    public function setCharityName($charityName)
    {
        $this->charityName = $charityName;
        return $this;
    }

    /**
     * Gets as donationPercent
     *
     * The percentage of the purchase price that the
     *  seller chooses to donate to the selected nonprofit
     *  organization. This percentage is displayed in the eBay for Charity listing.
     *  <b>Possible values</b>: 10.0 to 100.0.
     *  <b></b>
     *  <ul>
     *  <li>Percentages must increment by 5.0. </li>
     *  <li>Minimum donation
     *  percentages may be required for eBay for Charity listings, see
     *  <a href="http://pages.ebay.com/help/sell/selling-nonprofit.html">
     *  Selling to benefit nonprofit organizations</a> for
     *  details. </li>
     *  </ul>
     *  The <b>DonationPercent</b> field is required in an Add/Revise/Relist call if the seller will be donating a percentage of the sale proceeds for each sale generated by the listing.
     *
     * @return float
     */
    public function getDonationPercent()
    {
        return $this->donationPercent;
    }

    /**
     * Sets a new donationPercent
     *
     * The percentage of the purchase price that the
     *  seller chooses to donate to the selected nonprofit
     *  organization. This percentage is displayed in the eBay for Charity listing.
     *  <b>Possible values</b>: 10.0 to 100.0.
     *  <b></b>
     *  <ul>
     *  <li>Percentages must increment by 5.0. </li>
     *  <li>Minimum donation
     *  percentages may be required for eBay for Charity listings, see
     *  <a href="http://pages.ebay.com/help/sell/selling-nonprofit.html">
     *  Selling to benefit nonprofit organizations</a> for
     *  details. </li>
     *  </ul>
     *  The <b>DonationPercent</b> field is required in an Add/Revise/Relist call if the seller will be donating a percentage of the sale proceeds for each sale generated by the listing.
     *
     * @param float $donationPercent
     * @return self
     */
    public function setDonationPercent($donationPercent)
    {
        $this->donationPercent = $donationPercent;
        return $this;
    }

    /**
     * Gets as charityID
     *
     * The unique identifier that eBay creates and assigns to each nonprofit organization.
     *  <br>
     *  <br>
     *  The field is conditionally required in an Add/Revise/Relist call if the seller will be donating a percentage of the sale proceeds to this organization for each sale generated by the listing.
     *
     * @return string
     */
    public function getCharityID()
    {
        return $this->charityID;
    }

    /**
     * Sets a new charityID
     *
     * The unique identifier that eBay creates and assigns to each nonprofit organization.
     *  <br>
     *  <br>
     *  The field is conditionally required in an Add/Revise/Relist call if the seller will be donating a percentage of the sale proceeds to this organization for each sale generated by the listing.
     *
     * @param string $charityID
     * @return self
     */
    public function setCharityID($charityID)
    {
        $this->charityID = $charityID;
        return $this;
    }

    /**
     * Gets as mission
     *
     * The stated mission of the nonprofit charity organization. This mission statement is displayed in the eBay for Charity section of the View Item page.
     *  <br>
     *  <br>
     *
     * @return string
     */
    public function getMission()
    {
        return $this->mission;
    }

    /**
     * Sets a new mission
     *
     * The stated mission of the nonprofit charity organization. This mission statement is displayed in the eBay for Charity section of the View Item page.
     *  <br>
     *  <br>
     *
     * @param string $mission
     * @return self
     */
    public function setMission($mission)
    {
        $this->mission = $mission;
        return $this;
    }

    /**
     * Gets as logoURL
     *
     * The full URL to the nonprofit organization's logo image file. This logo image file is the image that is displayed in all eBay listings that benefit that charity. This field is returned as long as it is defined for the nonprofit organization.
     *
     * @return string
     */
    public function getLogoURL()
    {
        return $this->logoURL;
    }

    /**
     * Sets a new logoURL
     *
     * The full URL to the nonprofit organization's logo image file. This logo image file is the image that is displayed in all eBay listings that benefit that charity. This field is returned as long as it is defined for the nonprofit organization.
     *
     * @param string $logoURL
     * @return self
     */
    public function setLogoURL($logoURL)
    {
        $this->logoURL = $logoURL;
        return $this;
    }

    /**
     * Gets as status
     *
     * This enumeration value indicates whether or not the nonprofit organization is a valid eBay for Charity organization, and is able to receive proceeds from eBay sales.
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets a new status
     *
     * This enumeration value indicates whether or not the nonprofit organization is a valid eBay for Charity organization, and is able to receive proceeds from eBay sales.
     *
     * @param string $status
     * @return self
     */
    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * Gets as charityListing
     *
     * If this field is returned as <code>true</code>, a percentage of order line item's purchase price will be donated to a nonprofit organization.
     *
     * @return bool
     */
    public function getCharityListing()
    {
        return $this->charityListing;
    }

    /**
     * Sets a new charityListing
     *
     * If this field is returned as <code>true</code>, a percentage of order line item's purchase price will be donated to a nonprofit organization.
     *
     * @param bool $charityListing
     * @return self
     */
    public function setCharityListing($charityListing)
    {
        $this->charityListing = $charityListing;
        return $this;
    }

    public function xmlSerialize(\Sabre\Xml\Writer $writer): void
    {
        $this->xmlSerializeAttributes($writer);
        $this->xmlSerializeElements($writer);
    }

    protected function xmlSerializeAttributes(\Sabre\Xml\Writer $writer): void
    {
        Func::writeDefaultNamespace($writer, "urn:ebay:apis:eBLBaseComponents");
    }

    protected function xmlSerializeElements(\Sabre\Xml\Writer $writer): void
    {
        $value = $this->charityName;
        if (null !== $value) {
            $writer->writeElementNs(null, 'CharityName', null, (string) $value);
        }
        $value = $this->donationPercent;
        if (null !== $value) {
            $writer->writeElementNs(null, 'DonationPercent', null, (string) $value);
        }
        $value = $this->charityID;
        if (null !== $value) {
            $writer->writeElementNs(null, 'CharityID', null, (string) $value);
        }
        $value = $this->mission;
        if (null !== $value) {
            $writer->writeElementNs(null, 'Mission', null, (string) $value);
        }
        $value = $this->logoURL;
        if (null !== $value) {
            $writer->writeElementNs(null, 'LogoURL', null, (string) $value);
        }
        $value = $this->status;
        if (null !== $value) {
            $writer->writeElementNs(null, 'Status', null, (string) $value);
        }
        $value = $this->charityListing;
        if (null !== $value) {
            $writer->writeElementNs(null, 'CharityListing', null, ($value ? 'true' : 'false'));
        }
    }

    public static function xmlDeserialize(\Sabre\Xml\Reader $reader): mixed
    {
        return self::xmlRead($reader);
    }

    /**
     * Reads the element the reader is positioned on and moves past its end.
     */
    public static function xmlRead(\XMLReader $reader): \Nogrod\eBaySDK\Trading\CharityType
    {
        $self = new self();
        $self->xmlInitLists();
        Func::readObject($reader, $self);
        return $self;
    }

    protected function xmlInitLists(): void
    {
    }

    /**
     * Called by Func::readObject(): reads the attribute the reader is positioned on,
     * if it belongs to this type.
     */
    public function xmlReadAttribute(\XMLReader $reader): bool
    {
        return false;
    }

    /**
     * Called by Func::readObject(): reads the child element the reader is positioned
     * on, if it belongs to this type, and moves past its end.
     */
    public function xmlReadElement(\XMLReader $reader): bool
    {
        if ('urn:ebay:apis:eBLBaseComponents' === $reader->namespaceURI) {
            switch ($reader->localName) {
                case 'CharityName':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->charityName = $value;
                    }
                    return true;
                case 'DonationPercent':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->donationPercent = (float) $value;
                    }
                    return true;
                case 'CharityID':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->charityID = $value;
                    }
                    return true;
                case 'Mission':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->mission = $value;
                    }
                    return true;
                case 'LogoURL':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->logoURL = $value;
                    }
                    return true;
                case 'Status':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->status = $value;
                    }
                    return true;
                case 'CharityListing':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->charityListing = filter_var($value, FILTER_VALIDATE_BOOLEAN);
                    }
                    return true;
            }
        }
        return false;
    }

    protected function jsonProperties(): array
    {
        $data = [];
        $data['CharityName'] = $this->charityName;
        $data['DonationPercent'] = $this->donationPercent;
        $data['CharityID'] = $this->charityID;
        $data['Mission'] = $this->mission;
        $data['LogoURL'] = $this->logoURL;
        $data['Status'] = $this->status;
        $data['CharityListing'] = $this->charityListing;
        return $data;
    }

    public function jsonSerialize(): mixed
    {
        return array_filter($this->jsonProperties(), static fn ($v) => null !== $v);
    }
}
