<?php

namespace Nogrod\eBaySDK\Trading;

use Nogrod\XMLClientRuntime\Func;

/**
 * Class representing SKUDetailsType
 *
 * Describes or includes information associated with the SKU.
 * XSD Type: SKUDetailsType
 */
class SKUDetailsType implements \Sabre\Xml\XmlSerializable, \Sabre\Xml\XmlDeserializable
{
    /**
     * Stock Keeping Unit that serves as a unique identifier for an item.
     *  Many merchants assign a SKU number to an item of a specific type,
     *  size, and color. This way, they can keep track of how many products
     *  of each type, size, and color are selling, and they can re-stock
     *  their shelves according to customer demand. <br>
     *  <br>
     *  You can include a SKU when you list any item, and then use the SKU
     *  instead of (or in addition to) using the ItemID to track your
     *  inventory on eBay.<br>
     *  <br>
     *  For fixed-price items, if you set Item.InventoryTrackingmethod to
     *  SKU, you can use the SKU instead of ItemID as a unique ID when you
     *  revise the listing.<br>
     *  <br>
     *  Only returned when the listing included a SKU.
     *
     * @var string $sKU
     */
    private $sKU = null;

    /**
     * The price that the seller assigns to the item. If this value
     *  changes when the item is revised, the new value becomes the price.
     *  For a multi-variation listing, price is only returned at
     *  the variation level. <br>
     *  <br>
     *  You can revise this value using ReviseFixedPriceItem or ReviseInventoryStatus in the Trading API.
     *
     * @var \Nogrod\eBaySDK\Trading\AmountType $price
     */
    private $price = null;

    /**
     * The total number of items available for sale in the listing.
     *  For a multi-variation listing, the item quantity for each variation
     *  is returned at the variation level.
     *  <br>
     *  You can revise this value using ReviseFixedPriceItem or ReviseInventoryStatus in the Trading API.
     *
     * @var int $quantity
     */
    private $quantity = null;

    /**
     * The ID that uniquely identifies the item listing.
     *  The ID is generated by eBay after an item is listed.
     *  You cannot choose or revise this value.
     *
     * @var string $itemID
     */
    private $itemID = null;

    /**
     * Number of bids placed so far for the item.
     *  Returned only for auction-style listings if auctionItemDetails.includeBidCount has
     *  a value of true in the activeInventoryReportFilter of a Bulk Data Exchange Service
     *  startDownloadJob request.
     *  <br><br>
     *  See <a href="https://developer.ebay.com/DevZone/bulk-data-exchange/CallRef/startDownloadJob.html#Request.downloadRequestFilter.activeInventoryReportFilter" target="_blank">activeInventoryReportFilter</a>
     *
     * @var int $bidCount
     */
    private $bidCount = null;

    /**
     * Indicates whether the Reserve Price has been met for the listing.
     *  Returned only for auction-style listings if auctionItemDetails.includeReservePrice has
     *  a value of true in the activeInventoryReportFilter of a Bulk Data Exchange Service
     *  startDownloadJob request.
     *  <br><br>
     *  See <a href="https://developer.ebay.com/DevZone/bulk-data-exchange/CallRef/startDownloadJob.html#Request.downloadRequestFilter.activeInventoryReportFilter" target="_blank">activeInventoryReportFilter</a>
     *
     * @var bool $reserveMet
     */
    private $reserveMet = null;

    /**
     * Variations are multiple similar (but not identical) items in one
     *  fixed-price listing. For example, a clothing listing can
     *  contain items of the same brand that vary by color and size.
     *  Each variation specifies a combination of one of these
     *  colors and sizes. Each variation can have a different
     *  quantity and price.
     *
     * @var \Nogrod\eBaySDK\Trading\MerchantDataVariationType[] $variations
     */
    private $variations = null;

    /**
     * Gets as sKU
     *
     * Stock Keeping Unit that serves as a unique identifier for an item.
     *  Many merchants assign a SKU number to an item of a specific type,
     *  size, and color. This way, they can keep track of how many products
     *  of each type, size, and color are selling, and they can re-stock
     *  their shelves according to customer demand. <br>
     *  <br>
     *  You can include a SKU when you list any item, and then use the SKU
     *  instead of (or in addition to) using the ItemID to track your
     *  inventory on eBay.<br>
     *  <br>
     *  For fixed-price items, if you set Item.InventoryTrackingmethod to
     *  SKU, you can use the SKU instead of ItemID as a unique ID when you
     *  revise the listing.<br>
     *  <br>
     *  Only returned when the listing included a SKU.
     *
     * @return string
     */
    public function getSKU()
    {
        return $this->sKU;
    }

    /**
     * Sets a new sKU
     *
     * Stock Keeping Unit that serves as a unique identifier for an item.
     *  Many merchants assign a SKU number to an item of a specific type,
     *  size, and color. This way, they can keep track of how many products
     *  of each type, size, and color are selling, and they can re-stock
     *  their shelves according to customer demand. <br>
     *  <br>
     *  You can include a SKU when you list any item, and then use the SKU
     *  instead of (or in addition to) using the ItemID to track your
     *  inventory on eBay.<br>
     *  <br>
     *  For fixed-price items, if you set Item.InventoryTrackingmethod to
     *  SKU, you can use the SKU instead of ItemID as a unique ID when you
     *  revise the listing.<br>
     *  <br>
     *  Only returned when the listing included a SKU.
     *
     * @param string $sKU
     * @return self
     */
    public function setSKU($sKU)
    {
        $this->sKU = $sKU;
        return $this;
    }

    /**
     * Gets as price
     *
     * The price that the seller assigns to the item. If this value
     *  changes when the item is revised, the new value becomes the price.
     *  For a multi-variation listing, price is only returned at
     *  the variation level. <br>
     *  <br>
     *  You can revise this value using ReviseFixedPriceItem or ReviseInventoryStatus in the Trading API.
     *
     * @return \Nogrod\eBaySDK\Trading\AmountType
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Sets a new price
     *
     * The price that the seller assigns to the item. If this value
     *  changes when the item is revised, the new value becomes the price.
     *  For a multi-variation listing, price is only returned at
     *  the variation level. <br>
     *  <br>
     *  You can revise this value using ReviseFixedPriceItem or ReviseInventoryStatus in the Trading API.
     *
     * @param \Nogrod\eBaySDK\Trading\AmountType $price
     * @return self
     */
    public function setPrice(\Nogrod\eBaySDK\Trading\AmountType $price)
    {
        $this->price = $price;
        return $this;
    }

    /**
     * Gets as quantity
     *
     * The total number of items available for sale in the listing.
     *  For a multi-variation listing, the item quantity for each variation
     *  is returned at the variation level.
     *  <br>
     *  You can revise this value using ReviseFixedPriceItem or ReviseInventoryStatus in the Trading API.
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Sets a new quantity
     *
     * The total number of items available for sale in the listing.
     *  For a multi-variation listing, the item quantity for each variation
     *  is returned at the variation level.
     *  <br>
     *  You can revise this value using ReviseFixedPriceItem or ReviseInventoryStatus in the Trading API.
     *
     * @param int $quantity
     * @return self
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;
        return $this;
    }

    /**
     * Gets as itemID
     *
     * The ID that uniquely identifies the item listing.
     *  The ID is generated by eBay after an item is listed.
     *  You cannot choose or revise this value.
     *
     * @return string
     */
    public function getItemID()
    {
        return $this->itemID;
    }

    /**
     * Sets a new itemID
     *
     * The ID that uniquely identifies the item listing.
     *  The ID is generated by eBay after an item is listed.
     *  You cannot choose or revise this value.
     *
     * @param string $itemID
     * @return self
     */
    public function setItemID($itemID)
    {
        $this->itemID = $itemID;
        return $this;
    }

    /**
     * Gets as bidCount
     *
     * Number of bids placed so far for the item.
     *  Returned only for auction-style listings if auctionItemDetails.includeBidCount has
     *  a value of true in the activeInventoryReportFilter of a Bulk Data Exchange Service
     *  startDownloadJob request.
     *  <br><br>
     *  See <a href="https://developer.ebay.com/DevZone/bulk-data-exchange/CallRef/startDownloadJob.html#Request.downloadRequestFilter.activeInventoryReportFilter" target="_blank">activeInventoryReportFilter</a>
     *
     * @return int
     */
    public function getBidCount()
    {
        return $this->bidCount;
    }

    /**
     * Sets a new bidCount
     *
     * Number of bids placed so far for the item.
     *  Returned only for auction-style listings if auctionItemDetails.includeBidCount has
     *  a value of true in the activeInventoryReportFilter of a Bulk Data Exchange Service
     *  startDownloadJob request.
     *  <br><br>
     *  See <a href="https://developer.ebay.com/DevZone/bulk-data-exchange/CallRef/startDownloadJob.html#Request.downloadRequestFilter.activeInventoryReportFilter" target="_blank">activeInventoryReportFilter</a>
     *
     * @param int $bidCount
     * @return self
     */
    public function setBidCount($bidCount)
    {
        $this->bidCount = $bidCount;
        return $this;
    }

    /**
     * Gets as reserveMet
     *
     * Indicates whether the Reserve Price has been met for the listing.
     *  Returned only for auction-style listings if auctionItemDetails.includeReservePrice has
     *  a value of true in the activeInventoryReportFilter of a Bulk Data Exchange Service
     *  startDownloadJob request.
     *  <br><br>
     *  See <a href="https://developer.ebay.com/DevZone/bulk-data-exchange/CallRef/startDownloadJob.html#Request.downloadRequestFilter.activeInventoryReportFilter" target="_blank">activeInventoryReportFilter</a>
     *
     * @return bool
     */
    public function getReserveMet()
    {
        return $this->reserveMet;
    }

    /**
     * Sets a new reserveMet
     *
     * Indicates whether the Reserve Price has been met for the listing.
     *  Returned only for auction-style listings if auctionItemDetails.includeReservePrice has
     *  a value of true in the activeInventoryReportFilter of a Bulk Data Exchange Service
     *  startDownloadJob request.
     *  <br><br>
     *  See <a href="https://developer.ebay.com/DevZone/bulk-data-exchange/CallRef/startDownloadJob.html#Request.downloadRequestFilter.activeInventoryReportFilter" target="_blank">activeInventoryReportFilter</a>
     *
     * @param bool $reserveMet
     * @return self
     */
    public function setReserveMet($reserveMet)
    {
        $this->reserveMet = $reserveMet;
        return $this;
    }

    /**
     * Adds as variation
     *
     * Variations are multiple similar (but not identical) items in one
     *  fixed-price listing. For example, a clothing listing can
     *  contain items of the same brand that vary by color and size.
     *  Each variation specifies a combination of one of these
     *  colors and sizes. Each variation can have a different
     *  quantity and price.
     *
     * @return self
     * @param \Nogrod\eBaySDK\Trading\MerchantDataVariationType $variation
     */
    public function addToVariations(\Nogrod\eBaySDK\Trading\MerchantDataVariationType $variation)
    {
        if (!is_array($this->variations)) {
            throw new \LogicException('variations is a lazy iterable and cannot be appended to; set an array instead.');
        }
        $this->variations[] = $variation;
        return $this;
    }

    /**
     * isset variations
     *
     * Variations are multiple similar (but not identical) items in one
     *  fixed-price listing. For example, a clothing listing can
     *  contain items of the same brand that vary by color and size.
     *  Each variation specifies a combination of one of these
     *  colors and sizes. Each variation can have a different
     *  quantity and price.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetVariations($index)
    {
        return isset($this->variations[$index]);
    }

    /**
     * unset variations
     *
     * Variations are multiple similar (but not identical) items in one
     *  fixed-price listing. For example, a clothing listing can
     *  contain items of the same brand that vary by color and size.
     *  Each variation specifies a combination of one of these
     *  colors and sizes. Each variation can have a different
     *  quantity and price.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetVariations($index)
    {
        unset($this->variations[$index]);
    }

    /**
     * Gets as variations
     *
     * Variations are multiple similar (but not identical) items in one
     *  fixed-price listing. For example, a clothing listing can
     *  contain items of the same brand that vary by color and size.
     *  Each variation specifies a combination of one of these
     *  colors and sizes. Each variation can have a different
     *  quantity and price.
     *
     * @return iterable<\Nogrod\eBaySDK\Trading\MerchantDataVariationType>
     */
    public function getVariations()
    {
        return $this->variations;
    }

    /**
     * Sets a new variations
     *
     * Variations are multiple similar (but not identical) items in one
     *  fixed-price listing. For example, a clothing listing can
     *  contain items of the same brand that vary by color and size.
     *  Each variation specifies a combination of one of these
     *  colors and sizes. Each variation can have a different
     *  quantity and price.
     *
     * @param iterable<\Nogrod\eBaySDK\Trading\MerchantDataVariationType> $variations
     * @return self
     */
    public function setVariations(iterable $variations)
    {
        $this->variations = $variations;
        return $this;
    }

    public function xmlSerialize(\Sabre\Xml\Writer $writer): void
    {
        $this->xmlSerializeAttributes($writer);
        $this->xmlSerializeElements($writer);
    }

    protected function xmlSerializeAttributes(\Sabre\Xml\Writer $writer): void
    {
        Func::writeDefaultNamespace($writer, "urn:ebay:apis:eBLBaseComponents");
    }

    protected function xmlSerializeElements(\Sabre\Xml\Writer $writer): void
    {
        $value = $this->sKU;
        if (null !== $value) {
            $writer->writeElementNs(null, 'SKU', null, (string) $value);
        }
        $value = $this->price;
        if (null !== $value) {
            $writer->startElementNs(null, 'Price', null);
            $value->xmlSerialize($writer);
            $writer->endElement();
        }
        $value = $this->quantity;
        if (null !== $value) {
            $writer->writeElementNs(null, 'Quantity', null, (string) $value);
        }
        $value = $this->itemID;
        if (null !== $value) {
            $writer->writeElementNs(null, 'ItemID', null, (string) $value);
        }
        $value = $this->bidCount;
        if (null !== $value) {
            $writer->writeElementNs(null, 'BidCount', null, (string) $value);
        }
        $value = $this->reserveMet;
        if (null !== $value) {
            $writer->writeElementNs(null, 'ReserveMet', null, ($value ? 'true' : 'false'));
        }
        $value = $this->variations;
        if (null !== $value) {
            $open = false;
            foreach ($value as $v) {
                if (!$open) {
                    $writer->startElementNs(null, 'Variations', null);
                    $open = true;
                }
                $writer->startElementNs(null, 'Variation', null);
                $v->xmlSerialize($writer);
                $writer->endElement();
            }
            if ($open) {
                $writer->endElement();
            }
        }
    }

    public static function xmlDeserialize(\Sabre\Xml\Reader $reader): mixed
    {
        return self::xmlRead($reader);
    }

    /**
     * Reads the element the reader is positioned on and moves past its end.
     */
    public static function xmlRead(\XMLReader $reader): \Nogrod\eBaySDK\Trading\SKUDetailsType
    {
        $self = new self();
        $self->xmlInitLists();
        Func::readObject($reader, $self);
        return $self;
    }

    protected function xmlInitLists(): void
    {
        $this->variations = [];
    }

    /**
     * Called by Func::readObject(): reads the attribute the reader is positioned on,
     * if it belongs to this type.
     */
    public function xmlReadAttribute(\XMLReader $reader): bool
    {
        return false;
    }

    /**
     * Called by Func::readObject(): reads the child element the reader is positioned
     * on, if it belongs to this type, and moves past its end.
     */
    public function xmlReadElement(\XMLReader $reader): bool
    {
        if ('urn:ebay:apis:eBLBaseComponents' === $reader->namespaceURI) {
            switch ($reader->localName) {
                case 'SKU':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->sKU = $value;
                    }
                    return true;
                case 'Price':
                    $this->price = \Nogrod\eBaySDK\Trading\AmountType::xmlRead($reader);
                    return true;
                case 'Quantity':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->quantity = (int) $value;
                    }
                    return true;
                case 'ItemID':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->itemID = $value;
                    }
                    return true;
                case 'BidCount':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->bidCount = (int) $value;
                    }
                    return true;
                case 'ReserveMet':
                    $value = Func::readText($reader);
                    if ('' !== $value) {
                        $this->reserveMet = filter_var($value, FILTER_VALIDATE_BOOLEAN);
                    }
                    return true;
                case 'Variations':
                    $this->variations = Func::readList($reader, 'Variation', 'urn:ebay:apis:eBLBaseComponents', static fn (\XMLReader $reader) => \Nogrod\eBaySDK\Trading\MerchantDataVariationType::xmlRead($reader));
                    return true;
            }
        }
        return false;
    }
}
