<?php

namespace Nogrod\eBaySDK\Trading\Client;

use Sabre\Xml\Writer;

class TradingClassMap
{
    public static function Get(): array
    {
        return ['Time' => function (Writer $writer, $elem) {
            $value = $elem->format('H:i:s');
            if ($elem->getTimezone()->getOffset($elem) !== (new \DateTimeZone('UTC'))->getOffset($elem)) {
                $value .= $elem->format('P');
            }$writer->write($value);
        },
        'DateTime' => function (Writer $writer, $elem) {$writer->write($elem->format('Y-m-d\TH:i:s.v\Z'));},
        'Date' => function (Writer $writer, $elem) {$writer->write($elem->format('Y-m-d'));},];
    }

    public static function GetElements(): array
    {
        return [
        '{urn:ebay:apis:eBLBaseComponents}ActiveInventoryReport' => 'Nogrod\eBaySDK\Trading\ActiveInventoryReport',
        '{urn:ebay:apis:eBLBaseComponents}ActiveInventoryReportRequest' => 'Nogrod\eBaySDK\Trading\ActiveInventoryReportRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddFixedPriceItemRequest' => 'Nogrod\eBaySDK\Trading\AddFixedPriceItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddFixedPriceItemResponse' => 'Nogrod\eBaySDK\Trading\AddFixedPriceItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}AddItemRequest' => 'Nogrod\eBaySDK\Trading\AddItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddItemResponse' => 'Nogrod\eBaySDK\Trading\AddItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}AddItemsRequest' => 'Nogrod\eBaySDK\Trading\AddItemsRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddItemsResponse' => 'Nogrod\eBaySDK\Trading\AddItemsResponse',
        '{urn:ebay:apis:eBLBaseComponents}AddMemberMessageAAQToPartnerRequest' => 'Nogrod\eBaySDK\Trading\AddMemberMessageAAQToPartnerRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddMemberMessageAAQToPartnerResponse' => 'Nogrod\eBaySDK\Trading\AddMemberMessageAAQToPartnerResponse',
        '{urn:ebay:apis:eBLBaseComponents}AddMemberMessageRTQRequest' => 'Nogrod\eBaySDK\Trading\AddMemberMessageRTQRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddMemberMessageRTQResponse' => 'Nogrod\eBaySDK\Trading\AddMemberMessageRTQResponse',
        '{urn:ebay:apis:eBLBaseComponents}AddMemberMessagesAAQToBidderRequest' => 'Nogrod\eBaySDK\Trading\AddMemberMessagesAAQToBidderRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddMemberMessagesAAQToBidderResponse' => 'Nogrod\eBaySDK\Trading\AddMemberMessagesAAQToBidderResponse',
        '{urn:ebay:apis:eBLBaseComponents}AddOrderRequest' => 'Nogrod\eBaySDK\Trading\AddOrderRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddOrderResponse' => 'Nogrod\eBaySDK\Trading\AddOrderResponse',
        '{urn:ebay:apis:eBLBaseComponents}AddSecondChanceItemRequest' => 'Nogrod\eBaySDK\Trading\AddSecondChanceItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddSecondChanceItemResponse' => 'Nogrod\eBaySDK\Trading\AddSecondChanceItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}AddToItemDescriptionRequest' => 'Nogrod\eBaySDK\Trading\AddToItemDescriptionRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddToItemDescriptionResponse' => 'Nogrod\eBaySDK\Trading\AddToItemDescriptionResponse',
        '{urn:ebay:apis:eBLBaseComponents}AddToWatchListRequest' => 'Nogrod\eBaySDK\Trading\AddToWatchListRequest',
        '{urn:ebay:apis:eBLBaseComponents}AddToWatchListResponse' => 'Nogrod\eBaySDK\Trading\AddToWatchListResponse',
        '{urn:ebay:apis:eBLBaseComponents}BulkDataExchangeRequests' => 'Nogrod\eBaySDK\Trading\BulkDataExchangeRequests',
        '{urn:ebay:apis:eBLBaseComponents}BulkDataExchangeResponses' => 'Nogrod\eBaySDK\Trading\BulkDataExchangeResponses',
        '{urn:ebay:apis:eBLBaseComponents}CompleteSaleRequest' => 'Nogrod\eBaySDK\Trading\CompleteSaleRequest',
        '{urn:ebay:apis:eBLBaseComponents}CompleteSaleResponse' => 'Nogrod\eBaySDK\Trading\CompleteSaleResponse',
        '{urn:ebay:apis:eBLBaseComponents}ConfirmIdentityRequest' => 'Nogrod\eBaySDK\Trading\ConfirmIdentityRequest',
        '{urn:ebay:apis:eBLBaseComponents}ConfirmIdentityResponse' => 'Nogrod\eBaySDK\Trading\ConfirmIdentityResponse',
        '{urn:ebay:apis:eBLBaseComponents}DeleteMyMessagesRequest' => 'Nogrod\eBaySDK\Trading\DeleteMyMessagesRequest',
        '{urn:ebay:apis:eBLBaseComponents}DeleteMyMessagesResponse' => 'Nogrod\eBaySDK\Trading\DeleteMyMessagesResponse',
        '{urn:ebay:apis:eBLBaseComponents}EndFixedPriceItemRequest' => 'Nogrod\eBaySDK\Trading\EndFixedPriceItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}EndFixedPriceItemResponse' => 'Nogrod\eBaySDK\Trading\EndFixedPriceItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}EndItemRequest' => 'Nogrod\eBaySDK\Trading\EndItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}EndItemResponse' => 'Nogrod\eBaySDK\Trading\EndItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}EndItemsRequest' => 'Nogrod\eBaySDK\Trading\EndItemsRequest',
        '{urn:ebay:apis:eBLBaseComponents}EndItemsResponse' => 'Nogrod\eBaySDK\Trading\EndItemsResponse',
        '{urn:ebay:apis:eBLBaseComponents}ExtendSiteHostedPicturesRequest' => 'Nogrod\eBaySDK\Trading\ExtendSiteHostedPicturesRequest',
        '{urn:ebay:apis:eBLBaseComponents}ExtendSiteHostedPicturesResponse' => 'Nogrod\eBaySDK\Trading\ExtendSiteHostedPicturesResponse',
        '{urn:ebay:apis:eBLBaseComponents}FeeSettlementReport' => 'Nogrod\eBaySDK\Trading\FeeSettlementReport',
        '{urn:ebay:apis:eBLBaseComponents}FeeSettlementReportRequest' => 'Nogrod\eBaySDK\Trading\FeeSettlementReportRequest',
        '{urn:ebay:apis:eBLBaseComponents}FetchTokenRequest' => 'Nogrod\eBaySDK\Trading\FetchTokenRequest',
        '{urn:ebay:apis:eBLBaseComponents}FetchTokenResponse' => 'Nogrod\eBaySDK\Trading\FetchTokenResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetAccountRequest' => 'Nogrod\eBaySDK\Trading\GetAccountRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetAccountResponse' => 'Nogrod\eBaySDK\Trading\GetAccountResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetAdFormatLeadsRequest' => 'Nogrod\eBaySDK\Trading\GetAdFormatLeadsRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetAdFormatLeadsResponse' => 'Nogrod\eBaySDK\Trading\GetAdFormatLeadsResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetAllBiddersRequest' => 'Nogrod\eBaySDK\Trading\GetAllBiddersRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetAllBiddersResponse' => 'Nogrod\eBaySDK\Trading\GetAllBiddersResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetBestOffersRequest' => 'Nogrod\eBaySDK\Trading\GetBestOffersRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetBestOffersResponse' => 'Nogrod\eBaySDK\Trading\GetBestOffersResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetBidderListRequest' => 'Nogrod\eBaySDK\Trading\GetBidderListRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetBidderListResponse' => 'Nogrod\eBaySDK\Trading\GetBidderListResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetCategoriesRequest' => 'Nogrod\eBaySDK\Trading\GetCategoriesRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetCategoriesResponse' => 'Nogrod\eBaySDK\Trading\GetCategoriesResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetCategoryFeaturesRequest' => 'Nogrod\eBaySDK\Trading\GetCategoryFeaturesRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetCategoryFeaturesResponse' => 'Nogrod\eBaySDK\Trading\GetCategoryFeaturesResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetChallengeTokenRequest' => 'Nogrod\eBaySDK\Trading\GetChallengeTokenRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetChallengeTokenResponse' => 'Nogrod\eBaySDK\Trading\GetChallengeTokenResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetDescriptionTemplatesRequest' => 'Nogrod\eBaySDK\Trading\GetDescriptionTemplatesRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetDescriptionTemplatesResponse' => 'Nogrod\eBaySDK\Trading\GetDescriptionTemplatesResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetFeedbackRequest' => 'Nogrod\eBaySDK\Trading\GetFeedbackRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetFeedbackResponse' => 'Nogrod\eBaySDK\Trading\GetFeedbackResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetItemRequest' => 'Nogrod\eBaySDK\Trading\GetItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetItemResponse' => 'Nogrod\eBaySDK\Trading\GetItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetItemShippingRequest' => 'Nogrod\eBaySDK\Trading\GetItemShippingRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetItemShippingResponse' => 'Nogrod\eBaySDK\Trading\GetItemShippingResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetItemTransactionsRequest' => 'Nogrod\eBaySDK\Trading\GetItemTransactionsRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetItemTransactionsResponse' => 'Nogrod\eBaySDK\Trading\GetItemTransactionsResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetItemsAwaitingFeedbackRequest' => 'Nogrod\eBaySDK\Trading\GetItemsAwaitingFeedbackRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetItemsAwaitingFeedbackResponse' => 'Nogrod\eBaySDK\Trading\GetItemsAwaitingFeedbackResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetMemberMessagesRequest' => 'Nogrod\eBaySDK\Trading\GetMemberMessagesRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetMemberMessagesResponse' => 'Nogrod\eBaySDK\Trading\GetMemberMessagesResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetMessagePreferencesRequest' => 'Nogrod\eBaySDK\Trading\GetMessagePreferencesRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetMessagePreferencesResponse' => 'Nogrod\eBaySDK\Trading\GetMessagePreferencesResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetMyMessagesRequest' => 'Nogrod\eBaySDK\Trading\GetMyMessagesRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetMyMessagesResponse' => 'Nogrod\eBaySDK\Trading\GetMyMessagesResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetMyeBayBuyingRequest' => 'Nogrod\eBaySDK\Trading\GetMyeBayBuyingRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetMyeBayBuyingResponse' => 'Nogrod\eBaySDK\Trading\GetMyeBayBuyingResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetMyeBaySellingRequest' => 'Nogrod\eBaySDK\Trading\GetMyeBaySellingRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetMyeBaySellingResponse' => 'Nogrod\eBaySDK\Trading\GetMyeBaySellingResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetNotificationPreferencesRequest' => 'Nogrod\eBaySDK\Trading\GetNotificationPreferencesRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetNotificationPreferencesResponse' => 'Nogrod\eBaySDK\Trading\GetNotificationPreferencesResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetNotificationsUsageRequest' => 'Nogrod\eBaySDK\Trading\GetNotificationsUsageRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetNotificationsUsageResponse' => 'Nogrod\eBaySDK\Trading\GetNotificationsUsageResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetOrdersRequest' => 'Nogrod\eBaySDK\Trading\GetOrdersRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetOrdersResponse' => 'Nogrod\eBaySDK\Trading\GetOrdersResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetSellerEventsRequest' => 'Nogrod\eBaySDK\Trading\GetSellerEventsRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetSellerEventsResponse' => 'Nogrod\eBaySDK\Trading\GetSellerEventsResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetSellerListRequest' => 'Nogrod\eBaySDK\Trading\GetSellerListRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetSellerListResponse' => 'Nogrod\eBaySDK\Trading\GetSellerListResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetSellerTransactionsRequest' => 'Nogrod\eBaySDK\Trading\GetSellerTransactionsRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetSellerTransactionsResponse' => 'Nogrod\eBaySDK\Trading\GetSellerTransactionsResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetSessionIDRequest' => 'Nogrod\eBaySDK\Trading\GetSessionIDRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetSessionIDResponse' => 'Nogrod\eBaySDK\Trading\GetSessionIDResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetShippingDiscountProfilesRequest' => 'Nogrod\eBaySDK\Trading\GetShippingDiscountProfilesRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetShippingDiscountProfilesResponse' => 'Nogrod\eBaySDK\Trading\GetShippingDiscountProfilesResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetStoreCategoryUpdateStatusRequest' => 'Nogrod\eBaySDK\Trading\GetStoreCategoryUpdateStatusRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetStoreCategoryUpdateStatusResponse' => 'Nogrod\eBaySDK\Trading\GetStoreCategoryUpdateStatusResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetStoreRequest' => 'Nogrod\eBaySDK\Trading\GetStoreRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetStoreResponse' => 'Nogrod\eBaySDK\Trading\GetStoreResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetTaxTableRequest' => 'Nogrod\eBaySDK\Trading\GetTaxTableRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetTaxTableResponse' => 'Nogrod\eBaySDK\Trading\GetTaxTableResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetTokenStatusRequest' => 'Nogrod\eBaySDK\Trading\GetTokenStatusRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetTokenStatusResponse' => 'Nogrod\eBaySDK\Trading\GetTokenStatusResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetUserContactDetailsRequest' => 'Nogrod\eBaySDK\Trading\GetUserContactDetailsRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetUserContactDetailsResponse' => 'Nogrod\eBaySDK\Trading\GetUserContactDetailsResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetUserPreferencesRequest' => 'Nogrod\eBaySDK\Trading\GetUserPreferencesRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetUserPreferencesResponse' => 'Nogrod\eBaySDK\Trading\GetUserPreferencesResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetUserRequest' => 'Nogrod\eBaySDK\Trading\GetUserRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetUserResponse' => 'Nogrod\eBaySDK\Trading\GetUserResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetVeROReasonCodeDetailsRequest' => 'Nogrod\eBaySDK\Trading\GetVeROReasonCodeDetailsRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetVeROReasonCodeDetailsResponse' => 'Nogrod\eBaySDK\Trading\GetVeROReasonCodeDetailsResponse',
        '{urn:ebay:apis:eBLBaseComponents}GetVeROReportStatusRequest' => 'Nogrod\eBaySDK\Trading\GetVeROReportStatusRequest',
        '{urn:ebay:apis:eBLBaseComponents}GetVeROReportStatusResponse' => 'Nogrod\eBaySDK\Trading\GetVeROReportStatusResponse',
        '{urn:ebay:apis:eBLBaseComponents}GeteBayDetailsRequest' => 'Nogrod\eBaySDK\Trading\GeteBayDetailsRequest',
        '{urn:ebay:apis:eBLBaseComponents}GeteBayDetailsResponse' => 'Nogrod\eBaySDK\Trading\GeteBayDetailsResponse',
        '{urn:ebay:apis:eBLBaseComponents}GeteBayOfficialTimeRequest' => 'Nogrod\eBaySDK\Trading\GeteBayOfficialTimeRequest',
        '{urn:ebay:apis:eBLBaseComponents}GeteBayOfficialTimeResponse' => 'Nogrod\eBaySDK\Trading\GeteBayOfficialTimeResponse',
        '{urn:ebay:apis:eBLBaseComponents}LeaveFeedbackRequest' => 'Nogrod\eBaySDK\Trading\LeaveFeedbackRequest',
        '{urn:ebay:apis:eBLBaseComponents}LeaveFeedbackResponse' => 'Nogrod\eBaySDK\Trading\LeaveFeedbackResponse',
        '{urn:ebay:apis:eBLBaseComponents}NotificationMessage' => 'Nogrod\eBaySDK\Trading\NotificationMessage',
        '{urn:ebay:apis:eBLBaseComponents}OrderAckRequest' => 'Nogrod\eBaySDK\Trading\OrderAckRequest',
        '{urn:ebay:apis:eBLBaseComponents}OrderAckResponse' => 'Nogrod\eBaySDK\Trading\OrderAckResponse',
        '{urn:ebay:apis:eBLBaseComponents}OrderReport' => 'Nogrod\eBaySDK\Trading\OrderReport',
        '{urn:ebay:apis:eBLBaseComponents}OrderReportRequest' => 'Nogrod\eBaySDK\Trading\OrderReportRequest',
        '{urn:ebay:apis:eBLBaseComponents}PlaceOfferRequest' => 'Nogrod\eBaySDK\Trading\PlaceOfferRequest',
        '{urn:ebay:apis:eBLBaseComponents}PlaceOfferResponse' => 'Nogrod\eBaySDK\Trading\PlaceOfferResponse',
        '{urn:ebay:apis:eBLBaseComponents}RelistFixedPriceItemRequest' => 'Nogrod\eBaySDK\Trading\RelistFixedPriceItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}RelistFixedPriceItemResponse' => 'Nogrod\eBaySDK\Trading\RelistFixedPriceItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}RelistItemRequest' => 'Nogrod\eBaySDK\Trading\RelistItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}RelistItemResponse' => 'Nogrod\eBaySDK\Trading\RelistItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}RemoveFromWatchListRequest' => 'Nogrod\eBaySDK\Trading\RemoveFromWatchListRequest',
        '{urn:ebay:apis:eBLBaseComponents}RemoveFromWatchListResponse' => 'Nogrod\eBaySDK\Trading\RemoveFromWatchListResponse',
        '{urn:ebay:apis:eBLBaseComponents}RequesterCredentials' => 'Nogrod\eBaySDK\Trading\RequesterCredentials',
        '{urn:ebay:apis:eBLBaseComponents}RespondToBestOfferRequest' => 'Nogrod\eBaySDK\Trading\RespondToBestOfferRequest',
        '{urn:ebay:apis:eBLBaseComponents}RespondToBestOfferResponse' => 'Nogrod\eBaySDK\Trading\RespondToBestOfferResponse',
        '{urn:ebay:apis:eBLBaseComponents}RespondToFeedbackRequest' => 'Nogrod\eBaySDK\Trading\RespondToFeedbackRequest',
        '{urn:ebay:apis:eBLBaseComponents}RespondToFeedbackResponse' => 'Nogrod\eBaySDK\Trading\RespondToFeedbackResponse',
        '{urn:ebay:apis:eBLBaseComponents}ReviseFixedPriceItemRequest' => 'Nogrod\eBaySDK\Trading\ReviseFixedPriceItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}ReviseFixedPriceItemResponse' => 'Nogrod\eBaySDK\Trading\ReviseFixedPriceItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}ReviseInventoryStatusRequest' => 'Nogrod\eBaySDK\Trading\ReviseInventoryStatusRequest',
        '{urn:ebay:apis:eBLBaseComponents}ReviseInventoryStatusResponse' => 'Nogrod\eBaySDK\Trading\ReviseInventoryStatusResponse',
        '{urn:ebay:apis:eBLBaseComponents}ReviseItemRequest' => 'Nogrod\eBaySDK\Trading\ReviseItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}ReviseItemResponse' => 'Nogrod\eBaySDK\Trading\ReviseItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}ReviseMyMessagesFoldersRequest' => 'Nogrod\eBaySDK\Trading\ReviseMyMessagesFoldersRequest',
        '{urn:ebay:apis:eBLBaseComponents}ReviseMyMessagesFoldersResponse' => 'Nogrod\eBaySDK\Trading\ReviseMyMessagesFoldersResponse',
        '{urn:ebay:apis:eBLBaseComponents}ReviseMyMessagesRequest' => 'Nogrod\eBaySDK\Trading\ReviseMyMessagesRequest',
        '{urn:ebay:apis:eBLBaseComponents}ReviseMyMessagesResponse' => 'Nogrod\eBaySDK\Trading\ReviseMyMessagesResponse',
        '{urn:ebay:apis:eBLBaseComponents}RevokeTokenRequest' => 'Nogrod\eBaySDK\Trading\RevokeTokenRequest',
        '{urn:ebay:apis:eBLBaseComponents}RevokeTokenResponse' => 'Nogrod\eBaySDK\Trading\RevokeTokenResponse',
        '{urn:ebay:apis:eBLBaseComponents}SendInvoiceRequest' => 'Nogrod\eBaySDK\Trading\SendInvoiceRequest',
        '{urn:ebay:apis:eBLBaseComponents}SendInvoiceResponse' => 'Nogrod\eBaySDK\Trading\SendInvoiceResponse',
        '{urn:ebay:apis:eBLBaseComponents}SetMessagePreferencesRequest' => 'Nogrod\eBaySDK\Trading\SetMessagePreferencesRequest',
        '{urn:ebay:apis:eBLBaseComponents}SetMessagePreferencesResponse' => 'Nogrod\eBaySDK\Trading\SetMessagePreferencesResponse',
        '{urn:ebay:apis:eBLBaseComponents}SetNotificationPreferencesRequest' => 'Nogrod\eBaySDK\Trading\SetNotificationPreferencesRequest',
        '{urn:ebay:apis:eBLBaseComponents}SetNotificationPreferencesResponse' => 'Nogrod\eBaySDK\Trading\SetNotificationPreferencesResponse',
        '{urn:ebay:apis:eBLBaseComponents}SetShipmentTrackingInfoRequest' => 'Nogrod\eBaySDK\Trading\SetShipmentTrackingInfoRequest',
        '{urn:ebay:apis:eBLBaseComponents}SetShipmentTrackingInfoResponse' => 'Nogrod\eBaySDK\Trading\SetShipmentTrackingInfoResponse',
        '{urn:ebay:apis:eBLBaseComponents}SetShippingDiscountProfilesRequest' => 'Nogrod\eBaySDK\Trading\SetShippingDiscountProfilesRequest',
        '{urn:ebay:apis:eBLBaseComponents}SetShippingDiscountProfilesResponse' => 'Nogrod\eBaySDK\Trading\SetShippingDiscountProfilesResponse',
        '{urn:ebay:apis:eBLBaseComponents}SetStoreCategoriesRequest' => 'Nogrod\eBaySDK\Trading\SetStoreCategoriesRequest',
        '{urn:ebay:apis:eBLBaseComponents}SetStoreCategoriesResponse' => 'Nogrod\eBaySDK\Trading\SetStoreCategoriesResponse',
        '{urn:ebay:apis:eBLBaseComponents}SetTaxTableRequest' => 'Nogrod\eBaySDK\Trading\SetTaxTableRequest',
        '{urn:ebay:apis:eBLBaseComponents}SetTaxTableResponse' => 'Nogrod\eBaySDK\Trading\SetTaxTableResponse',
        '{urn:ebay:apis:eBLBaseComponents}SetUserNotesRequest' => 'Nogrod\eBaySDK\Trading\SetUserNotesRequest',
        '{urn:ebay:apis:eBLBaseComponents}SetUserNotesResponse' => 'Nogrod\eBaySDK\Trading\SetUserNotesResponse',
        '{urn:ebay:apis:eBLBaseComponents}SetUserPreferencesRequest' => 'Nogrod\eBaySDK\Trading\SetUserPreferencesRequest',
        '{urn:ebay:apis:eBLBaseComponents}SetUserPreferencesResponse' => 'Nogrod\eBaySDK\Trading\SetUserPreferencesResponse',
        '{urn:ebay:apis:eBLBaseComponents}UploadSiteHostedPicturesRequest' => 'Nogrod\eBaySDK\Trading\UploadSiteHostedPicturesRequest',
        '{urn:ebay:apis:eBLBaseComponents}UploadSiteHostedPicturesResponse' => 'Nogrod\eBaySDK\Trading\UploadSiteHostedPicturesResponse',
        '{urn:ebay:apis:eBLBaseComponents}ValidateChallengeInputRequest' => 'Nogrod\eBaySDK\Trading\ValidateChallengeInputRequest',
        '{urn:ebay:apis:eBLBaseComponents}ValidateChallengeInputResponse' => 'Nogrod\eBaySDK\Trading\ValidateChallengeInputResponse',
        '{urn:ebay:apis:eBLBaseComponents}ValidateTestUserRegistrationRequest' => 'Nogrod\eBaySDK\Trading\ValidateTestUserRegistrationRequest',
        '{urn:ebay:apis:eBLBaseComponents}ValidateTestUserRegistrationResponse' => 'Nogrod\eBaySDK\Trading\ValidateTestUserRegistrationResponse',
        '{urn:ebay:apis:eBLBaseComponents}VeROReportItemsRequest' => 'Nogrod\eBaySDK\Trading\VeROReportItemsRequest',
        '{urn:ebay:apis:eBLBaseComponents}VeROReportItemsResponse' => 'Nogrod\eBaySDK\Trading\VeROReportItemsResponse',
        '{urn:ebay:apis:eBLBaseComponents}VerifyAddFixedPriceItemRequest' => 'Nogrod\eBaySDK\Trading\VerifyAddFixedPriceItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}VerifyAddFixedPriceItemResponse' => 'Nogrod\eBaySDK\Trading\VerifyAddFixedPriceItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}VerifyAddItemRequest' => 'Nogrod\eBaySDK\Trading\VerifyAddItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}VerifyAddItemResponse' => 'Nogrod\eBaySDK\Trading\VerifyAddItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}VerifyAddSecondChanceItemRequest' => 'Nogrod\eBaySDK\Trading\VerifyAddSecondChanceItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}VerifyAddSecondChanceItemResponse' => 'Nogrod\eBaySDK\Trading\VerifyAddSecondChanceItemResponse',
        '{urn:ebay:apis:eBLBaseComponents}VerifyRelistItemRequest' => 'Nogrod\eBaySDK\Trading\VerifyRelistItemRequest',
        '{urn:ebay:apis:eBLBaseComponents}VerifyRelistItemResponse' => 'Nogrod\eBaySDK\Trading\VerifyRelistItemResponse',
        ];
    }

    public static function GetNamespaces(): array
    {
        return ['urn:ebay:apis:eBLBaseComponents' => '',];
    }
}
