xml_client:
  namespaces:
    'http://www.ebay.com/marketplace/services': 'Nogrod\eBaySDK\BulkDataExchange'
  destinations_php:
    'Nogrod\eBaySDK\BulkDataExchange': src/BulkDataExchange
  destinations_jms:
    'Nogrod\eBaySDK\BulkDataExchange': metadata/BulkDataExchange
  metadata:
    'wsdl/BulkDataExchange.wsdl': ~
  configs_jms:
    xml_cdata: false
