xml_client:
  namespaces:
    'http://www.ebay.com/marketplace/services': 'Nogrod\eBaySDK\FileTransfer'
  destinations_php:
    'Nogrod\eBaySDK\FileTransfer': src/FileTransfer
  destinations_jms:
    'Nogrod\eBaySDK\FileTransfer': metadata/FileTransfer
  metadata:
    'wsdl/FileTransfer.wsdl': ~
  aliases:
    'http://www.w3.org/2001/XMLSchema':
      anyType: 'string'
      anySimpleType: 'string'
  configs_jms:
    xml_cdata: false
