xml_client:
  namespaces:
    'http://www.ebay.com/marketplace/search/v1/services': 'Nogrod\eBaySDK\Finding'
  destinations_php:
    'Nogrod\eBaySDK\Finding': src/Finding
  destinations_jms:
    'Nogrod\eBaySDK\Finding': metadata/Finding
  metadata:
    'wsdl/Finding.wsdl': ~
  configs_jms:
    xml_cdata: false
  naming_strategy: long
