Nogrod\eBaySDK\Trading\ApplicationDeliveryPreferencesType:
    virtual_properties:
        ns_prop:
            exp: '"urn:ebay:apis:eBLBaseComponents"'
            serialized_name: xmlns
            xml_attribute: true
    properties:
        applicationURL:
            expose: true
            access_type: public_method
            serialized_name: ApplicationURL
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getApplicationURL
                setter: setApplicationURL
            type: string
        applicationEnable:
            expose: true
            access_type: public_method
            serialized_name: ApplicationEnable
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getApplicationEnable
                setter: setApplicationEnable
            type: string
        alertEmail:
            expose: true
            access_type: public_method
            serialized_name: AlertEmail
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getAlertEmail
                setter: setAlertEmail
            type: string
        alertEnable:
            expose: true
            access_type: public_method
            serialized_name: AlertEnable
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getAlertEnable
                setter: setAlertEnable
            type: string
        notificationPayloadType:
            expose: true
            access_type: public_method
            serialized_name: NotificationPayloadType
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getNotificationPayloadType
                setter: setNotificationPayloadType
            type: string
        deviceType:
            expose: true
            access_type: public_method
            serialized_name: DeviceType
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getDeviceType
                setter: setDeviceType
            type: string
        payloadVersion:
            expose: true
            access_type: public_method
            serialized_name: PayloadVersion
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getPayloadVersion
                setter: setPayloadVersion
            type: string
        deliveryURLDetails:
            expose: true
            access_type: public_method
            serialized_name: DeliveryURLDetails
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getDeliveryURLDetails
                setter: setDeliveryURLDetails
            xml_list:
                inline: true
                entry_name: DeliveryURLDetails
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            type: array<Nogrod\eBaySDK\Trading\DeliveryURLDetailType>
