Nogrod\eBaySDK\Trading\ProductListingDetailsType:
    virtual_properties:
        ns_prop:
            exp: '"urn:ebay:apis:eBLBaseComponents"'
            serialized_name: xmlns
            xml_attribute: true
    properties:
        includeStockPhotoURL:
            expose: true
            access_type: public_method
            serialized_name: IncludeStockPhotoURL
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getIncludeStockPhotoURL
                setter: setIncludeStockPhotoURL
            type: bool
        useStockPhotoURLAsGallery:
            expose: true
            access_type: public_method
            serialized_name: UseStockPhotoURLAsGallery
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getUseStockPhotoURLAsGallery
                setter: setUseStockPhotoURLAsGallery
            type: bool
        stockPhotoURL:
            expose: true
            access_type: public_method
            serialized_name: StockPhotoURL
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getStockPhotoURL
                setter: setStockPhotoURL
            type: string
        copyright:
            expose: true
            access_type: public_method
            serialized_name: Copyright
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getCopyright
                setter: setCopyright
            xml_list:
                inline: true
                entry_name: Copyright
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            type: array<string>
        productReferenceID:
            expose: true
            access_type: public_method
            serialized_name: ProductReferenceID
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getProductReferenceID
                setter: setProductReferenceID
            type: string
        detailsURL:
            expose: true
            access_type: public_method
            serialized_name: DetailsURL
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getDetailsURL
                setter: setDetailsURL
            type: string
        productDetailsURL:
            expose: true
            access_type: public_method
            serialized_name: ProductDetailsURL
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getProductDetailsURL
                setter: setProductDetailsURL
            type: string
        returnSearchResultOnDuplicates:
            expose: true
            access_type: public_method
            serialized_name: ReturnSearchResultOnDuplicates
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getReturnSearchResultOnDuplicates
                setter: setReturnSearchResultOnDuplicates
            type: bool
        iSBN:
            expose: true
            access_type: public_method
            serialized_name: ISBN
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getISBN
                setter: setISBN
            type: string
        uPC:
            expose: true
            access_type: public_method
            serialized_name: UPC
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getUPC
                setter: setUPC
            type: string
        eAN:
            expose: true
            access_type: public_method
            serialized_name: EAN
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getEAN
                setter: setEAN
            type: string
        brandMPN:
            expose: true
            access_type: public_method
            serialized_name: BrandMPN
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getBrandMPN
                setter: setBrandMPN
            type: Nogrod\eBaySDK\Trading\BrandMPNType
        useFirstProduct:
            expose: true
            access_type: public_method
            serialized_name: UseFirstProduct
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getUseFirstProduct
                setter: setUseFirstProduct
            type: bool
        includeeBayProductDetails:
            expose: true
            access_type: public_method
            serialized_name: IncludeeBayProductDetails
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getIncludeeBayProductDetails
                setter: setIncludeeBayProductDetails
            type: bool
        nameValueList:
            expose: true
            access_type: public_method
            serialized_name: NameValueList
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getNameValueList
                setter: setNameValueList
            xml_list:
                inline: true
                entry_name: NameValueList
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            type: array<Nogrod\eBaySDK\Trading\NameValueListType>
