Nogrod\eBaySDK\Trading\ProductSuggestionsType:
    virtual_properties:
        ns_prop:
            exp: '"urn:ebay:apis:eBLBaseComponents"'
            serialized_name: xmlns
            xml_attribute: true
    properties:
        productSuggestion:
            expose: true
            access_type: public_method
            serialized_name: ProductSuggestion
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getProductSuggestion
                setter: setProductSuggestion
            xml_list:
                inline: true
                entry_name: ProductSuggestion
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            type: array<Nogrod\eBaySDK\Trading\ProductSuggestionType>
