Nogrod\eBaySDK\MerchantData\ProductFamilyType:
    virtual_properties:
        ns_prop:
            exp: '"urn:ebay:apis:eBLBaseComponents"'
            serialized_name: xmlns
            xml_attribute: true
    properties:
        hasMoreChildren:
            expose: true
            access_type: public_method
            serialized_name: hasMoreChildren
            accessor:
                getter: getHasMoreChildren
                setter: setHasMoreChildren
            xml_attribute: true
            type: bool
        parentProduct:
            expose: true
            access_type: public_method
            serialized_name: ParentProduct
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getParentProduct
                setter: setParentProduct
            type: Nogrod\eBaySDK\MerchantData\ProductType
        familyMembers:
            expose: true
            access_type: public_method
            serialized_name: FamilyMembers
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getFamilyMembers
                setter: setFamilyMembers
            xml_list:
                inline: true
                entry_name: FamilyMembers
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            type: array<Nogrod\eBaySDK\MerchantData\ProductType>
