Nogrod\eBaySDK\MerchantData\ProductSearchResultType:
    virtual_properties:
        ns_prop:
            exp: '"urn:ebay:apis:eBLBaseComponents"'
            serialized_name: xmlns
            xml_attribute: true
    properties:
        iD:
            expose: true
            access_type: public_method
            serialized_name: ID
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getID
                setter: setID
            type: string
        numProducts:
            expose: true
            access_type: public_method
            serialized_name: NumProducts
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getNumProducts
                setter: setNumProducts
            type: string
        attributeSet:
            expose: true
            access_type: public_method
            serialized_name: AttributeSet
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getAttributeSet
                setter: setAttributeSet
            xml_list:
                inline: true
                entry_name: AttributeSet
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            type: array<Nogrod\eBaySDK\MerchantData\ResponseAttributeSetType>
        displayStockPhotos:
            expose: true
            access_type: public_method
            serialized_name: DisplayStockPhotos
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getDisplayStockPhotos
                setter: setDisplayStockPhotos
            type: bool
