Nogrod\eBaySDK\MerchantData\ProductFinderConstraintType:
    virtual_properties:
        ns_prop:
            exp: '"urn:ebay:apis:eBLBaseComponents"'
            serialized_name: xmlns
            xml_attribute: true
    properties:
        displayName:
            expose: true
            access_type: public_method
            serialized_name: DisplayName
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getDisplayName
                setter: setDisplayName
            type: string
        displayValue:
            expose: true
            access_type: public_method
            serialized_name: DisplayValue
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getDisplayValue
                setter: setDisplayValue
            type: string
