Nogrod\eBaySDK\MerchantData\ProductPricingDetailsType:
    virtual_properties:
        ns_prop:
            exp: '"urn:ebay:apis:eBLBaseComponents"'
            serialized_name: xmlns
            xml_attribute: true
    properties:
        minimumSoldPrice:
            expose: true
            access_type: public_method
            serialized_name: MinimumSoldPrice
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getMinimumSoldPrice
                setter: setMinimumSoldPrice
            type: Nogrod\eBaySDK\MerchantData\AmountType
        maximumSoldPrice:
            expose: true
            access_type: public_method
            serialized_name: MaximumSoldPrice
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getMaximumSoldPrice
                setter: setMaximumSoldPrice
            type: Nogrod\eBaySDK\MerchantData\AmountType
        averageSoldPrice:
            expose: true
            access_type: public_method
            serialized_name: AverageSoldPrice
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getAverageSoldPrice
                setter: setAverageSoldPrice
            type: Nogrod\eBaySDK\MerchantData\AmountType
        lastSoldPrice:
            expose: true
            access_type: public_method
            serialized_name: LastSoldPrice
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getLastSoldPrice
                setter: setLastSoldPrice
            type: Nogrod\eBaySDK\MerchantData\AmountType
        minimumSoldPriceOverall:
            expose: true
            access_type: public_method
            serialized_name: MinimumSoldPriceOverall
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getMinimumSoldPriceOverall
                setter: setMinimumSoldPriceOverall
            type: Nogrod\eBaySDK\MerchantData\AmountType
        maximumSoldPriceOverall:
            expose: true
            access_type: public_method
            serialized_name: MaximumSoldPriceOverall
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getMaximumSoldPriceOverall
                setter: setMaximumSoldPriceOverall
            type: Nogrod\eBaySDK\MerchantData\AmountType
        averageSoldPriceOverall:
            expose: true
            access_type: public_method
            serialized_name: AverageSoldPriceOverall
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getAverageSoldPriceOverall
                setter: setAverageSoldPriceOverall
            type: Nogrod\eBaySDK\MerchantData\AmountType
        lastSoldPriceOverall:
            expose: true
            access_type: public_method
            serialized_name: LastSoldPriceOverall
            xml_element:
                cdata: false
                namespace: 'urn:ebay:apis:eBLBaseComponents'
            accessor:
                getter: getLastSoldPriceOverall
                setter: setLastSoldPriceOverall
            type: Nogrod\eBaySDK\MerchantData\AmountType
